### ISSUE TITLE
Docs not correct for Mac users

### ISSUE THREAD

**Issue by fergusmeiklejohn** [ionide/docs#5]
The docs aren't correct for mac users. So for example the Intellisense section says "you can see quick info for each method by either pressing Ctrl+Space or clicking the info icon". On mac this has no effect. Mostly Ctrl needs to be swapped with Command on Mac, but Command+Space is a system command so it triggers the system function not ionide's intellisense.

Now as a mac user I'm confused:
1. Is this feature only for Windows users?
2. If I need to remap the command what's it called?

**Comment by fergusmeiklejohn** [comment]
This documentation problem negatively affects the software. I go to the docs and see a feature but can't use it on my mac.
The same function exists out of the box in VSMac.  So now is MSMac "better" than Ionide on Mac? That would be an annoying conclusion.
Check out these simple screen grabs from VSMac and the Ionide. 
![screen shot 2018-05-14 at 08 55 00](https://user-images.githubusercontent.com/11864025/39974040-7e694764-5758-11e8-8b7b-cd8b2984962b.png)
![screen shot 2018-05-14 at 08 59 15](https://user-images.githubusercontent.com/11864025/39974041-7e909e2c-5758-11e8-8137-8081c04f7d7f.png)

Because the docs don't work for me (as a mac user) the experience with VSMac seems better than Ionide.

**Comment by inosik** [comment]
Maybe you have some other extension or a custom keybinding which remaps <kbd>Ctrl</kbd>+<kbd>Space</kbd>? It works fine for me on macOS.
